detection:
  model  : "yolov8"
  weight : "weights/yolov8l.pt"
  imgsz  : [640,640]
  conf   : 0.25
  classes: [0,24,25,26,28,67]
  verbose: False
  device : "cuda"
  kwargs : null 


track:
  model: "byte_track"
  kwargs:
    frame_rate: 30
    track_thresh: 0.25
    track_buffer: 20
    match_thresh: 0.7 # higher match thresh means more objects are matched
    mot20: False


checker:
  track_history_len: 15 # frames
  is_not_moving_checker_len: 45 # frames
  is_moving_threshold: 15 # in pixel

  