detection:
  model  : "yolov5"
  weight : "weights/5s_14_5_10h6.pt"
  imgsz  : [640,640]
  conf   : 0.25
  classes: null
  verbose: False
  device : "cuda"
  kwargs : null 

track:
  model: "byte_track"
  kwargs:
    frame_rate: 30
    track_thresh: 0.25
    track_buffer: 20
    match_thresh: 0.7 # higher match thresh means more objects are matched
    mot20: False

inspector:
  confirm_thresh: 10 # in frames
  max_euclidean_distance: 40
  window_size: 20
  tolerance: 15
  variation_thresh: 0.15

use_slicer: False

slicer:
  slice_wh: [320,320]
  overlap_ratio_wh: [0.,0.]
  iou_threshold: 0.5
